### ISSUE TITLE
feature request - filter based on kinds

### ISSUE THREAD

**Issue by dtdannen** [mikedilger/chorus#30]
I'd like an open relay, but one that only allows kinds 5000-7000, would this be possible?

**Comment by mikedilger** [comment]
Yes.  But you have to make a minor edit to the source code.

There is a function in `src/nostr.rs` called `screen_incoming_event()` where you can add this:

````rust
if event.kind().as_u16() < 5000 || event.kind().as_u16() >= 7000 {
    return false;
}
````

Put this before the `Accept if an open relay` comment.

Then set `open_relay = true` in your config file

Are you using it for a chat server like what hodlbod is doing recently?

**Comment by dtdannen** [comment]
Awesome thanks.

I'm using it for DVM related events (I run [dvmdash.live](https://dvmdash.live/about/)).
