### ISSUE TITLE
URL returned from Blossom PUT request contains port

### ISSUE THREAD

**Issue by tealeaf-dot-dev** [mikedilger/chorus#32]
### Steps to replicate

* run Chorus behind nginx
* upload an image using any client (nostrudel, bouquet)
* returned URL contains the port in the form http://chorus.tealeaf.dev:8000/be998131037dbd2acb86171708b2f6225cb840cf6e11be032e9e5bd0eb1046d5.jfif , breaking things client side

### Notes

* the image upload and file serving are working https://chorus.tealeaf.dev/be998131037dbd2acb86171708b2f6225cb840cf6e11be032e9e5bd0eb1046d5.jfif

**Comment by mikedilger** [comment]
Thanks for the report. I"ll look into it when I get back tomorrow.

**Comment by tealeaf-dot-dev** [comment]
Thanks Mike

**Comment by mikedilger** [comment]
Ok I believe I have it fixed on the master branch.

Because you are running chorus behind a proxy, you will need to set a new configuration variable "base_url" to the real front-end URL.   I missed this bug because I don't use a proxy.

**Comment by tealeaf-dot-dev** [comment]
Working! Thank you
