### ISSUE TITLE
 URL returned from Blossom PUT request is http when should be https

### ISSUE THREAD

**Issue by tealeaf-dot-dev** [mikedilger/chorus#33]
### Steps to replicate

* run Chorus behind nginx
* nginx is handling TLS so configure Chorus with use_tls = false
* upload an image using any client (nosrudel, bouquet)
* returned URL is http not https http://chorus.tealeaf.dev:8000/be998131037dbd2acb86171708b2f6225cb840cf6e11be032e9e5bd0eb1046d5.jfif

### Notes

Looks like line 242 in config.rs is applied
`            (false, true) => Scheme::HTTP,`

**Comment by mikedilger** [comment]
Thanks for the report. I"ll look into it when I get back tomorrow.

**Comment by mikedilger** [comment]
See #32, the same fix applies to this one.

**Comment by tealeaf-dot-dev** [comment]
All good. Thanks
